In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
my_list=[1,2,3,4,5,6]

In [5]:
my_list

[1, 2, 3, 4, 5, 6]

In [6]:
type(my_list)

list

In [7]:
arr=np.array(my_list)

In [8]:
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
type(arr)

numpy.ndarray

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.arange(3.0)

array([0., 1., 2.])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20,10) #1st arg < 2nd arg otherwise it  will return empty array

array([], dtype=int32)

In [16]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(10,10)

array([], dtype=int32)

In [19]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)

In [ ]:
np.arange(0,10,3)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(5,dtype=int)

In [ ]:
np.zeros((2,2),dtype=int)

In [ ]:
n=(3,4)
print(np.zeros(n,dtype=int))

In [ ]:
print(np.ones(n,dtype=int))

In [ ]:
np.random.rand(5)

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.randint(2,4)

In [ ]:
np.random.randint(2,20)

In [ ]:
np.random.randint(10,20,3)

In [ ]:
np.random.randint(30,20,5)

In [ ]:
np.random.randint(-30,20,5)

In [ ]:
np.random.randint(10,40,(10,10))

In [ ]:
np.random.randint(1,100,(12,12))

In [ ]:
np.arange(1,10).reshape(3,3)

In [ ]:
np.arange(1,10).reshape(3,4)

In [ ]:
np.arange(1,13).reshape(3,4)

In [ ]:
np.arange(1,13).reshape(6,2)

In [ ]:
np.arange(1,13).reshape(12,1)

In [ ]:
b=np.random.randint(10,20,(5,4))

In [ ]:
b

In [ ]:
type(b)

In [ ]:
b[:]

In [ ]:
b[1:3]

In [ ]:
b[1,2]

In [ ]:
b[0:5]

In [ ]:
b[1,3]

In [ ]:
b[2:3]

In [ ]:
b[0:-2]

In [ ]:
b[0,2]

In [ ]:
b[-5,-3]

In [ ]:
b[-4,2]

OPERATIONS

In [ ]:
a=np.random.randint(10,20,2)

In [ ]:
a

In [ ]:
id(a)

In [ ]:
a

In [20]:
arr2 = np.random.randint(0,100,(10,10))

In [21]:
arr2

array([[61, 72, 35,  2,  2, 74, 83, 79, 17, 87],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [91, 62, 77, 96, 83, 89, 31, 72, 91, 25],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [19, 56, 85, 60,  3, 68, 27, 70, 27, 60],
       [82, 17, 21,  7, 68, 22, 88, 73, 86, 75]])

In [22]:
arr2[:]

array([[61, 72, 35,  2,  2, 74, 83, 79, 17, 87],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [91, 62, 77, 96, 83, 89, 31, 72, 91, 25],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [19, 56, 85, 60,  3, 68, 27, 70, 27, 60],
       [82, 17, 21,  7, 68, 22, 88, 73, 86, 75]])

In [23]:
arr2[0:5]

array([[61, 72, 35,  2,  2, 74, 83, 79, 17, 87],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24]])

In [24]:
arr2[1,5]

87

In [25]:
arr2[-5,5]

19

In [26]:
arr2

array([[61, 72, 35,  2,  2, 74, 83, 79, 17, 87],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [91, 62, 77, 96, 83, 89, 31, 72, 91, 25],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [19, 56, 85, 60,  3, 68, 27, 70, 27, 60],
       [82, 17, 21,  7, 68, 22, 88, 73, 86, 75]])

In [27]:
arr2[::-1]

array([[82, 17, 21,  7, 68, 22, 88, 73, 86, 75],
       [19, 56, 85, 60,  3, 68, 27, 70, 27, 60],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [91, 62, 77, 96, 83, 89, 31, 72, 91, 25],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [61, 72, 35,  2,  2, 74, 83, 79, 17, 87]])

In [28]:
arr2[::-2]

array([[82, 17, 21,  7, 68, 22, 88, 73, 86, 75],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26]])

In [29]:
arr2

array([[61, 72, 35,  2,  2, 74, 83, 79, 17, 87],
       [18,  0, 15, 15,  0, 87, 68, 31, 29, 26],
       [92, 96, 52, 25, 92, 71, 17, 72, 68, 13],
       [44, 97, 82, 21, 61, 67,  1, 27, 53, 62],
       [ 8, 64, 58, 15, 13, 68, 38, 22, 18, 24],
       [35, 48, 29, 74, 55, 19, 49, 27, 50, 56],
       [91, 62, 77, 96, 83, 89, 31, 72, 91, 25],
       [35, 14, 83, 38, 54, 93, 85, 54, 10, 33],
       [19, 56, 85, 60,  3, 68, 27, 70, 27, 60],
       [82, 17, 21,  7, 68, 22, 88, 73, 86, 75]])

In [30]:
arr2.max()

97

In [31]:
arr2.min()

0

In [32]:
arr2.mean()

49.14

In [33]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [34]:
from numpy import *
x=median(arr2)
print(x)


53.5


In [35]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

INDEXING

In [49]:
mat = np.arange(0,100).reshape(10,10) 

In [50]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
row = 4
col = 5

In [52]:
row

4

In [53]:
col

5

In [54]:
mat[row,col]

45

In [55]:
mat[4,5]

45

In [56]:
col=6

In [57]:
col

6

In [58]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
mat[:,col] #to print a column

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [60]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
row

4

In [62]:
mat[row,:] #to print a row

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [63]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
mat[1,4]

14

In [65]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [66]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [67]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [70]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])